version: '3.8'
services:
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: deploy
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3300:3306'